from enum import Enum


class TunerSignals(Enum):
    CHANGE_TUNER_TO_CLASSIC = 0
    CHANGE_TUNER_TO_ELECTRIC = 1
    CHANGE_TUNER_TO_ACOUSTIC = 2


class SideMenuEvents(Enum):
    CHANGE_TUNING = 0
    CHANGE_GENRE = 1


class TopBarSignals(Enum):
    GUITAR_TUNING_CLICK = 0
    RECORDING_CLICK = 1
    CHORD_DETECTION_CLICK = 2
    METRONOME_CLICK = 3
    UPLOAD_CLICK = 4
    PITCH_TRAINING_CLICK = 5


class AppWidgetTypes(Enum):
    CONTENT = 0
    SIDE_MENU = 1
    TOP_BAR = 2
    TUNER_SIDE_MENU = 3
    METRONOME_SIDE_MENU = 4
    CLASSIC_TUNER_CONTENT = 5
    ELECTRIC_TUNER_CONTENT = 6
    ACOUSTIC_TUNER_CONTENT = 7
    RECORDING_CONTENT = 8
    CHORD_DETECTION_CONTENT = 9
    METRONOME_CONTENT = 10
    UPLOAD_CONTENT = 11
    PITCH_TRAINING_CONTENT = 12
